config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :coocos

   root 'coocos#index'

end

app/models/cooco.rb
class Cooco < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :coocos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coocos_controller.rb
class CoocosController < ApplicationController
  before_action :set_cooco, only: [:show, :edit, :update, :destroy]

  # GET /coocos
  # GET /coocos.json
  def index
    @coocos = Cooco.all
  end

  # GET /coocos/1
  # GET /coocos/1.json
  def show
  end

  # GET /coocos/new
  def new
    @cooco = Cooco.new
  end

  # GET /coocos/1/edit
  def edit
  end

  # POST /coocos
  # POST /coocos.json
  def create
    @cooco = Cooco.new(cooco_params)

    respond_to do |format|
      if @cooco.save
        format.html { redirect_to @cooco, notice: 'Cooco was successfully created.' }
        format.json { render :show, status: :created, location: @cooco }
      else
        format.html { render :new }
        format.json { render json: @cooco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coocos/1
  # PATCH/PUT /coocos/1.json
  def update
    respond_to do |format|
      if @cooco.update(cooco_params)
        format.html { redirect_to @cooco, notice: 'Cooco was successfully updated.' }
        format.json { render :show, status: :ok, location: @cooco }
      else
        format.html { render :edit }
        format.json { render json: @cooco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coocos/1
  # DELETE /coocos/1.json
  def destroy
    @cooco.destroy
    respond_to do |format|
      format.html { redirect_to coocos_url, notice: 'Cooco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooco
      @cooco = Cooco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cooco_params
      params.require(:cooco).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  before_action :set_user, only: [:show, :edit, :update, :destroy]

   # GET /
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @usero }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coocos_helper.rb
module CoocosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/coocos/_form.html.erb
<%= form_for(@cooco) do |f| %>
  <% if @cooco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cooco.errors.count, "error") %> prohibited this cooco from being saved:</h2>

      <ul>
      <% @cooco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coocos/edit.html.erb
<h1>Editing cooco</h1>

<%= render 'form' %>

<%= link_to 'Show', @cooco %> |
<%= link_to 'Back', coocos_path %>

app/views/coocos/index.html.erb
<h1>Lamentele</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coocos.each do |cooco| %>
      <tr>
        <td><%= cooco.content %></td>
        <td><%= link_to cooco.user.name + ' ' + cooco.user.surname , cooco.user %></td>
        <td><%= link_to 'Show', cooco %></td>
        <td><%= link_to 'Edit', edit_cooco_path(cooco) %></td>
        <td><%= link_to 'Destroy', cooco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cooco', new_cooco_path %>

app/views/coocos/new.html.erb
<h1>New cooco</h1>

<%= render 'form' %>

<%= link_to 'Back', coocos_path %>

app/views/coocos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lamento:</strong>
  <%= @cooco.content %>
</p>

<p>
  <strong>Autore:</strong>
  <%= @cooco.user.name + ' '+ @cooco.user.surname %>
</p>

<%= link_to 'Edit', edit_cooco_path(@cooco) %> |
<%= link_to 'Back', coocos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sigmiapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this@user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div id="name" class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div id="surname" class="field">
      <%= f.label :surname %><br>
      <%= f.text_field :surname %>
    </div>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Modifica utente</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Utenti</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cognome</th>
      <th>Descrizione</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>Nuovo utente</h1>

<%= render 'form' %>

<%= link_to 'Back', coocos_path %>

app/views/users/show.html.erb
<p>
  <strong>Utente:</strong>
  <%= @user.name+' '+@user.surname %>
</p>

<p>
  <strong>Qualcosa su di me:</strong>
  <%= @user.description %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>